
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb
        app: mongodb
  selector:
    matchLabels:
      app: mongodb
  spec:
    containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /data/db
            name: mongodb-data
        ports:
          - containerPort: 27017      
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

