version: '3'
services:

  #pyspark:
  #  container_name: pyspark-modeltrainer
  #  build: ./pyspark
  #  environment:
  #    - MODELS_MOUNTPATH=/mnt/models
  #  volumes:
  #    - ./pyspark/models:/mnt/models

  jarbuilder:
    container_name: jarbuilder
    build: ./jar_builder
    environment:
      #Name of the root directory where our spark-scala project files are located.
      - PROJECT_NAME=flight_prediction 
    volumes:
      - ./jar_builder/scala_projects:/mnt/scala_projects/
