version: '3'
services:

  mongodb:
    container_name: mongodb
    build: ./mongodb
    ports:
      - "27017:27017" # remember the port expose syntax is HOST:CONTAINER !
    volumes:
      - mongodbdata:/data/mongodb
    networks:
      - flight_prediction_network

  webserver:
    container_name: webserver
    build: ./flask
    ports:
      - "1212:80"
    networks:
      - flight_prediction_network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - flight_prediction_network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1" #Create topic named flight_delay_classification_request. Partitions: 1, Replicas:1.
    networks:
      - flight_prediction_network

  spark-master:
    container_name: spark-master
    image: bitnami/spark:2.4.4
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
    volumes:
      - ./spark/models/:/job_data/models #Bind mount to mount models dir on each spark node
    networks:
      - flight_prediction_network

  spark-worker-1:
    container_name: spark-worker-1
    image: bitnami/spark:2.4.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
    - '8081:8081'
    volumes:
      - ./spark/models/:/job_data/models  #Bind mount to mount models dir on each spark node
    networks:
      - flight_prediction_network

volumes:
  mongodbdata:

networks:
  flight_prediction_network:
    driver: bridge